
services:
  # 웹 애플리케이션 서비스
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: ocr-service:latest
    container_name: ocr-web
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
      - ./models:/app/models
      - ./configs:/app/configs
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis

  # 작업자 서비스 (OCR 처리)
  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
    image: ocr-service-worker:latest
    container_name: ocr-worker
    restart: unless-stopped
    volumes:
      - ./storage:/app/storage
      - ./models:/app/models
      - ./configs:/app/configs
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis

  # Redis 서비스 (작업 큐와 캐시)
  redis:
    image: redis:6-alpine
    container_name: ocr-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis-data:
