# 기본 설정
app:
  debug: false
  log_level: INFO
  api_host: 0.0.0.0
  api_port: 8000
  web_host: 0.0.0.0
  web_port: 8000
  secret_key: "change-this-to-a-secure-secret"

# 작업 큐 설정
queue:
  redis_url: redis://localhost:6379/0
  queue_name: ocr_tasks
  max_workers: 4
  timeout: 3600

# 스토리지 설정
storage:
  type: local       # local, s3, gcs
  local_path: ./storage
  s3_bucket: ocr-documents
  gcs_bucket: ocr-documents
  cache_enabled: true
  cache_ttl: 3600

# OCR 엔진 설정
ocr:
  use_custom_model: true
  use_tesseract: true
  use_google_vision: true
  use_azure_form: true
  model_dir: ./models
  
  # 앙상블 가중치
  ensemble_weights:
    custom_model: 0.5
    tesseract: 0.2
    google_vision: 0.2
    azure_form: 0.1
  
  # 신뢰도 임계값
  confidence_threshold: 0.85
  
  # 특수 항목 처리 설정
  special_items:
    detect_stamps: true
    detect_handwriting: true
    detect_strikethrough: true
  
  # 언어 설정
  supported_languages:
    jpn: 일본어
    eng: 영어
    kor: 한국어
    chi_sim: 중국어 간체
    chi_tra: 중국어 번체
  
  default_language: jpn

# 문서 처리 설정
document:
  pdf_dpi: 300
  max_pdf_pages: 100
  image_max_size: 4000
  batch_size: 8

# 추출 설정
extraction:
  llm:
    provider: openai       # openai, azure_openai, anthropic
    openai_model: gpt-4
    anthropic_model: claude-3-haiku-20240307
    temperature: 0.1
    max_tokens: 4000
  
  # 기본 추출 필드 (웹 UI에서 설정 가능)
  default_fields:
    - name: invoice_number
      type: text
      context: 청구서 번호|請求書番号|インボイス番号|No\.|番号
      regex: (\d{1,3}[\-\.]\d{1,3}[\-\.]\d{1,5})
    
    - name: date
      type: date
      context: 날짜|発行日|日付|date
      regex: (\d{4}[-/年\.]{1,2}\d{1,2}[-/月\.]{1,2}\d{1,2}[日]?)
    
    - name: total_amount
      type: amount
      context: 총액|合計|総額|total
      regex: ([¥￥]?\s*[\d,\.]+\s*[円]?)
    
    - name: company_name
      type: company
      context: 회사명|会社名|企業名|company
    
    - name: tax_amount
      type: amount
      context: 세금|税額|消費税|tax
      regex: ([¥￥]?\s*[\d,\.]+\s*[円]?)

# 웹 UI 설정
web:
  items_per_page: 20
  upload_max_size: 20971520  # 20MB
  session_lifetime: 86400    # 24 hours (in seconds)
  auth_enabled: true
  user_registration: false   # 새 사용자 등록 허용
